# -*- coding: utf-8 -*-
"""Adiciona novas fontes em sources.json para os itens do radar 06.05.2026."""
import json

with open('sources.json', encoding='utf-8') as f:
    src_data = json.load(f)

new_sources_section = {"_section": "=== NOVAS FONTES (ADICIONADAS 2026-05-08) ==="}

new_sources = [
    # Aceleradoras / Open Innovation
    {"id": "chips-ju", "name": "Chips JU / Chips Venture Forum", "url": "https://www.chips-ju.europa.eu/", "type": "european", "category": "Semicondutores, deep-tech", "access_method": "web", "access_status": "ok", "priority": "medium", "description": "Chips Joint Undertaking. Venture forum para startups de semicondutores no SEMICON Europa."},
    {"id": "amcc-testbed", "name": "AMCC Test Bed (Aveiro Media Competence Center)", "url": "https://testbed.a-mcc.eu/", "type": "national", "category": "Media test bed (PCI/NOS/UA/AMCC/Google)", "access_method": "web", "access_status": "ok", "priority": "medium", "description": "Test bed do consorcio AMCC para SMEs e startups do setor media."},
    {"id": "pci-aveiro", "name": "PCI - Creative Science Park Aveiro", "url": "https://pci.pt/", "type": "national", "category": "Parque de ciencia, test beds, incubacao", "access_method": "web", "access_status": "ok", "priority": "medium", "description": "Parque de Ciencia e Inovacao de Aveiro. Coordena varios test beds (AMCC, Smart Connected Spaces)."},
    {"id": "tasmu-qatar", "name": "TASMU Accelerator (Qatar MCIT)", "url": "https://accelerator.tasmu.gov.qa/", "type": "international", "category": "Aceleradora Qatar - smart cities, health, transport", "access_method": "web", "access_status": "ok", "priority": "low", "description": "Programa de aceleracao do Ministerio de Comunicacoes e IT do Qatar."},
    {"id": "28digital", "name": "28DIGITAL / EIT Digital", "url": "https://28digital.eu/", "type": "european", "category": "Aceleracao deep-tech digital, KIC EIT", "access_method": "web", "access_status": "ok", "priority": "medium", "description": "Plataforma da KIC EIT Digital com varios programas (Mentor Me, VIP, Champions)."},
    {"id": "infineon-startup", "name": "Infineon Startup Challenge", "url": "https://silicon-saxony.de/sisax-events/infineon-startup-challenge-2026-humanoid-robotics/", "type": "international", "category": "Hardware, robotica humanoide, semicondutores", "access_method": "web", "access_status": "ok", "priority": "medium", "description": "Programa de aceleracao Infineon + Silicon Saxony para startups de hardware (humanoid robotics em 2026)."},
    {"id": "eudis", "name": "EU Defence Innovation Scheme (EUDIS)", "url": "https://eudis.europa.eu/", "type": "european", "category": "Defesa, dual-use technology", "access_method": "web", "access_status": "ok", "priority": "medium", "description": "Programa europeu de inovacao em defesa. Inclui Business Accelerator (120K voucher)."},
    {"id": "scale-her", "name": "SCALE HER", "url": "https://scale-her-project.eu/", "type": "european", "category": "Aceleracao mulheres em deep tech", "access_method": "web", "access_status": "ok", "priority": "medium", "description": "Aceleradora EU para startups lideradas por mulheres em digital e deep tech."},
    {"id": "jarvis-eu", "name": "JARVIS Project", "url": "https://jarvis-project.eu/", "type": "european", "category": "Human-robot interaction, cascade funding", "access_method": "web", "access_status": "ok", "priority": "medium", "description": "Projeto Horizon Europe sobre interacao humano-robo. Open calls com financiamento ate 130K."},
    {"id": "aiod-platform", "name": "AI on Demand Platform (AIoD)", "url": "https://www.aiodp.ai/", "type": "european", "category": "Plataforma EU de IA, cascade funding", "access_method": "web", "access_status": "ok", "priority": "medium", "description": "Plataforma colaborativa europeia para IA. Cascade funding ate 60K para SMEs com TRL 7+."},
    {"id": "mastercard-fintechs", "name": "Mastercard For Fintechs", "url": "https://www.mastercard.com/europe/en/innovation/partner-with-us/mastercardforfintechs.html", "type": "international", "category": "Programa CVC fintech", "access_method": "web", "access_status": "ok", "priority": "low", "description": "Programa Mastercard Europa para fintechs (Pre-seed, Seed, Series A) em PT, ES, IT, FR, BE, NL."},
    {"id": "abanca-innova", "name": "ABANCA Innova", "url": "https://abancainnova.com/", "type": "international", "category": "Venture Client banco - fintech, IA, cripto", "access_method": "web", "access_status": "ok", "priority": "low", "description": "Programa Venture Client do banco ABANCA. Foco em IA, criptoativos e processos de tokenizacao."},
    {"id": "cotec-portugal", "name": "COTEC Portugal", "url": "https://cotecportugal.pt/", "type": "national", "category": "Inovacao empresarial, premios", "access_method": "web", "access_status": "ok", "priority": "medium", "description": "Associacao Empresarial para a Inovacao. Co-organiza com Santander o Premio Inovacao na Internacionalizacao."},
    {"id": "eit-urban-mobility", "name": "EIT Urban Mobility", "url": "https://www.eiturbanmobility.eu/", "type": "european", "category": "KIC mobilidade urbana - calls, aceleradoras", "access_method": "web", "access_status": "ok", "priority": "medium", "description": "Knowledge & Innovation Community sobre mobilidade urbana. Multiplos programas: Strategic Innovation, Citizens on the Move, Startup Creation."},
    {"id": "poliempreende", "name": "Poliempreende", "url": "https://poliempreende.com/", "type": "national", "category": "Concurso ideias politecnicos", "access_method": "web", "access_status": "ok", "priority": "low", "description": "Maior iniciativa nacional de empreendedorismo no ensino superior politecnico."},
    {"id": "tef-health", "name": "TEF-Health (Testing & Experimentation Facility)", "url": "https://tefhealth.eu/", "type": "european", "category": "Testing facility AI/robotica saude", "access_method": "web", "access_status": "ok", "priority": "medium", "description": "Projeto Digital Europe Programme. Acesso subsidiado a testes, validacao e certificacao para SMEs em IA e robotica de saude."},
    {"id": "bial-fundacao", "name": "Fundacao BIAL", "url": "https://www.fundacaobial.com/", "type": "national", "category": "Premios e bolsas em ciencias da saude", "access_method": "web", "access_status": "ok", "priority": "low", "description": "Fundacao BIAL em parceria com Ordem dos Medicos atribui o Premio Maria de Sousa (5 x 30K para investigadores ate 35 anos)."},
    {"id": "jewel-eurocluster", "name": "JEWEL Eurocluster", "url": "https://www.clustercollaboration.eu/content/jewel-eurocluster-open-call-1-nzt-demo-projects", "type": "european", "category": "Eurocluster - net-zero manufacturing", "access_method": "web", "access_status": "ok", "priority": "medium", "description": "Eurocluster JEWEL. Cascade funding para projetos demo de tecnologias net-zero industriais."},
    {"id": "nttdata-fundacao", "name": "Fundacao NTT Data (eAwards)", "url": "https://globaleawards.com/pt/portugal/", "type": "international", "category": "Premio empreendedorismo tecnologico", "access_method": "web", "access_status": "ok", "priority": "low", "description": "Fundacao NTT Data organiza os eAwards Portugal (10K nacional, 100K final internacional)."},
    {"id": "loreal-unesco", "name": "L Oreal-UNESCO For Women in Science", "url": "https://www.forwomeninscience.com/", "type": "international", "category": "Premio mulheres na ciencia", "access_method": "web", "access_status": "ok", "priority": "low", "description": "Premios anuais L Oreal Foundation + UNESCO. 5 premios internacionais de 100K (Fisica, Matematica, Quimica, Ciencias da Terra)."},
    {"id": "incm-selos-digital", "name": "INCM - Selos de Maturidade Digital", "url": "https://selosmaturidadedigital.incm.pt/", "type": "national", "category": "Certificacao maturidade digital (PRR)", "access_method": "web", "access_status": "ok", "priority": "medium", "description": "Imprensa Nacional Casa da Moeda. Certificacao bronze/prata/ouro em sustentabilidade, ciberseguranca, privacidade e acessibilidade. Financiado pelo PRR."},
    {"id": "ctt-1520", "name": "CTT 1520 Startup Program", "url": "https://www.ctt.pt/grupo-ctt/a-empresa/inovacao-e-startups/1520-startup-program/index", "type": "national", "category": "Programa CVC CTT", "access_method": "web", "access_status": "ok", "priority": "low", "description": "Programa de inovacao aberta dos CTT para startups (open innovation, partnerships)."},
    {"id": "aws-startup-loft", "name": "AWS Startup Loft Accelerator EMEA", "url": "https://aws-startup-lofts.com/emea/program/accelerator", "type": "international", "category": "Aceleradora cloud equity-free", "access_method": "web", "access_status": "ok", "priority": "low", "description": "Programa AWS de 10 semanas equity-free para startups early-stage com creditos AWS ate 25K."},
    {"id": "ccc-centro", "name": "CCC-Centro - Centro de Competencias em Ciberseguranca", "url": "https://www.ccc-centro.pt/", "type": "national", "category": "Apoio ciberseguranca regional", "access_method": "web", "access_status": "ok", "priority": "low", "description": "Centro de competencias em ciberseguranca da regiao Centro. Servicos gratuitos a entidades publicas e SMEs."},
    {"id": "euipo-sme-fund", "name": "EUIPO SME Fund", "url": "https://www.euipo.europa.eu/en/sme-corner/sme-fund", "type": "european", "category": "Vouchers IP (marcas, patentes, designs)", "access_method": "web", "access_status": "ok", "priority": "medium", "description": "Fundo gerido pelo EUIPO. Vouchers de reembolso para SMEs em registos de marcas, patentes, designs (ate 75% reembolso)."},
    # VCs / CVCs
    {"id": "c2-capital", "name": "C2 Capital Partners", "url": "https://c2capital.pt/", "type": "national", "category": "Private equity / VC - Expansion Capital, Energy", "access_method": "web", "access_status": "ok", "priority": "medium", "description": "PE/VC portuguesa desde 2009 (ex-Capital Criativo). 430M EUR AUM. Foco em SMEs familiares e clean energy."},
    {"id": "perseo-iberdrola", "name": "PERSEO - Iberdrola Ventures", "url": "https://www.iberdrola.com/about-us/our-innovation-model/international-startup-program-perseo", "type": "international", "category": "CVC energia, sustentabilidade", "access_method": "web", "access_status": "ok", "priority": "low", "description": "Programa CVC Iberdrola desde 2008. Mais de 200M EUR investidos em startups de energia, IA, eletrificacao."},
    {"id": "sogrape-ventures", "name": "Sogrape Ventures (gerido por Beta Capital)", "url": "https://ventures.sogrape.com/", "type": "national", "category": "CVC bebidas - precision viticulture, beverage tech", "access_method": "web", "access_status": "ok", "priority": "low", "description": "CVC Sogrape de 5M EUR. Foco em startups disruptivas com aplicacao na cadeia de valor do vinho/bebidas."},
    {"id": "transatlantic-highway", "name": "Transatlantic Highway Ventures", "url": "https://www.thv.vc/", "type": "national", "category": "VC pre-seed - agentic AI, B2B", "access_method": "web", "access_status": "ok", "priority": "low", "description": "Fundo VC para startups portuguesas de agentic AI a escalar para o mercado dos EUA. Tickets 50K-200K."},
    {"id": "trind-ventures", "name": "Trind Ventures", "url": "https://trind.vc/", "type": "european", "category": "VC seed-stage - consumer, marketplaces, B2B PLG", "access_method": "web", "access_status": "ok", "priority": "low", "description": "Fundo VC baseado em Tallinn (55M EUR). Investe em startups europeias incluindo Portugal. Tickets 100K-1M."},
    {"id": "lince-capital", "name": "Lince Capital", "url": "https://lince-capital.com/", "type": "national", "category": "VC seed - digital health, healthtech, software", "access_method": "web", "access_status": "ok", "priority": "medium", "description": "VC portuguesa desde 2016. Investe em early-stage portuguesas (digital health, software). Tickets 250K-5M+. Portfolio inclui Sword Health, Feedzai."},
    {"id": "daskapital", "name": "Daskapital", "url": "https://daskapital.eu/", "type": "national", "category": "Crowdfunding/crowdlending para SMEs", "access_method": "web", "access_status": "ok", "priority": "low", "description": "Plataforma de crowdfunding portuguesa. Daslending (medio prazo) e Dasfactoring (curto prazo via creditos)."},
    {"id": "produtech-dih", "name": "PRODUTECH DIH / DIH-squared", "url": "https://dih.produtech.org/", "type": "european", "category": "Digital Innovation Hub robotica e manufactura", "access_method": "web", "access_status": "ok", "priority": "medium", "description": "DIH portugues integrado no consortio europeu DIH-squared. Apoio a startups e PMEs em robotica e fabrico agil."},
]

sources_list = src_data['sources']
existing_ids = {src.get('id') for src in sources_list if 'id' in src}
to_add = [new_sources_section] + [s for s in new_sources if s['id'] not in existing_ids]
sources_list.extend(to_add)
src_data['_meta']['updated'] = '2026-05-08'
src_data['_meta']['total_sources'] = len([s for s in sources_list if 'id' in s])

with open('sources.json', 'w', encoding='utf-8') as f:
    json.dump(src_data, f, indent=2, ensure_ascii=False)

added = len(to_add) - 1
print(f'Adicionadas {added} fontes novas em sources.json')
print(f'Total fontes agora: {src_data["_meta"]["total_sources"]}')
